Issue #10 fix with test
WeTransfer/Mocker pull request #12
Opened 2018-09-17 13:49 UTC by fporcaro

I added the test and the fix.  If you keep the test without the fix, you will see the problem and the fix for Mock == seems to work and didn't break the other tests.

2018-09-18 20:47 UTC, fporcaro commented
I saw the Travis build failed, but looking at the fastlane output, I couldn't tell what the issue was

2018-10-02 07:08 UTC, AvdLee requested changes
Great work! I see that CI is failing, but your tests are succeeding. I will look into the CI issues, you can ignore them.

For this PR; would you mind adding a test for URLs including a query matching?

2018-10-02 07:08 UTC, AvdLee commented on MockerTests/MockerTests.swift
> +        let simpleURL = URL(string: "https://host.com/api/resource")
You can force unwrap this one which enables you to remove the XCTFail on line 241

2018-10-02 07:08 UTC, AvdLee commented on MockerTests/MockerTests.swift
> +    func testComposedURLMatch() {
Can you add a describing documentation starting with "It should .. "

2018-10-26 12:43 UTC, AvdLee commented
https://github.com/WeTransfer/Mocker/pull/14 Will fix the unwraps, you can merge that in once it's merged.

2018-10-31 14:04 UTC, AvdLee commented
You can merge #14 in now!

2018-11-05 15:47 UTC, fporcaro commented
Changes should be made and merged into my branch.  Looks like the CI passed.  Let me know what else you need from me.

2018-11-06 09:14 UTC, AvdLee approved these changes

2018-11-06 09:14 UTC, merged