Support collection types as a top level object
WeTransfer/Mocker pull request #125
Opened 2022-08-05 07:53 UTC by batuhansk

As you know, top level collection objects are also valid JSON. But, Mocker wasn't support them because of the casting that made up in the `MockingURLProtocol.swift`

2022-08-05 07:54 UTC, batuhansk commented
refers to this issue #119

2022-08-08 11:48 UTC, AvdLee requested changes
Thanks, this makes sense! Can you update the tests as well to verify this is working as expected?

2022-08-09 13:11 UTC, BasThomas approved these changes
This is awesome!

2022-08-09 13:24 UTC, peagasilva approved these changes
🚀

2022-08-10 08:44 UTC, AvdLee commented
@batuhansk could you pull latest `master` into your PR so CI succeeds? Thanks!

2022-08-10 09:08 UTC, batuhansk commented
> @batuhansk could you pull latest `master` into your PR so CI succeeds? Thanks!

sure, done!

2022-08-10 09:23 UTC, wetransferplatform commented
<!--
  0 failure: 
  0 warning: 
  2 messages
  2 markdown notices
  DangerID: danger-id-Danger;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  View more details on <a href="https://app.bitrise.io/build/3b393fcd-5f8c-46a6-b5ff-63c0cceeff03" target="_blank">Bitrise</a>
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>MockerTests: Executed 26 tests (0 failed, 0 retried, 0 skipped) in 1.610 seconds</td>
    </tr>
  </tbody>
</table>

### SwiftLint found issues

| Severity | File | Reason |
| -------- | ---- | ------ |
Error | MockingURLProtocol.swift:41 | Line should be 160 characters or less: currently 166 characters (`line_length`) |
Error | MockingURLProtocol.swift:44 | Line should be 160 characters or less: currently 200 characters (`line_length`) |
Warning | MockingURLProtocol.swift:101 | Line should be 140 characters or less: currently 147 characters (`line_length`) |
Error | MockingURLProtocol.swift:105 | Line should be 160 characters or less: currently 221 characters (`line_length`) |
Error | Mock.swift:8 | Line should be 160 characters or less: currently 177 characters (`line_length`) |
Warning | Mock.swift:49 | Line should be 140 characters or less: currently 155 characters (`line_length`) |
Error | Mock.swift:81 | Line should be 160 characters or less: currently 211 characters (`line_length`) |
Error | Mock.swift:84 | Line should be 160 characters or less: currently 208 characters (`line_length`) |
Error | Mock.swift:93 | Line should be 160 characters or less: currently 287 characters (`line_length`) |
Warning | Mock.swift:122 | Line should be 140 characters or less: currently 142 characters (`line_length`) |
Warning | Mock.swift:129 | Line should be 140 characters or less: currently 141 characters (`line_length`) |
Error | Mock.swift:136 | Line should be 160 characters or less: currently 246 characters (`line_length`) |
Error | Mock.swift:137 | Line should be 160 characters or less: currently 236 characters (`line_length`) |
Warning | Mock.swift:148 | Line should be 140 characters or less: currently 150 characters (`line_length`) |
Warning | Mock.swift:149 | Line should be 140 characters or less: currently 153 characters (`line_length`) |
Warning | Mock.swift:185 | Line should be 140 characters or less: currently 159 characters (`line_length`) |
Error | Mock.swift:195 | Line should be 160 characters or less: currently 168 characters (`line_length`) |
Warning | MockerTests.swift:163 | Line should be 140 characters or less: currently 151 characters (`line_length`) |
Warning | MockerTests.swift:181 | Line should be 140 characters or less: currently 149 characters (`line_length`) |
Warning | MockerTests.swift:239 | Line should be 140 characters or less: currently 154 characters (`line_length`) |
Warning | MockerTests.swift:52 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |
Warning | MockerTests.swift:71 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |
Warning | MockerTests.swift:94 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |
Warning | MockerTests.swift:116 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |
Warning | MockerTests.swift:149 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |
Warning | MockerTests.swift:165 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |
Warning | MockerTests.swift:183 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |
Warning | MockerTests.swift:206 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |
Warning | MockerTests.swift:259 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |
Warning | MockerTests.swift:457 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |
Warning | MockerTests.swift:491 | Chained function calls should be either on the same line, or one per line. (`multiline_function_chains`) |
Warning | MockerTests.swift:334 | Lines should not have trailing whitespace. (`trailing_whitespace`) |

## Code Coverage Report
| Name | Coverage ||
| --- | --- | --- |
Mocker.framework | 87.93% | ✅

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against accd9f54ae6658f11835a7773b9e40c4ad085701
</p>

2022-08-10 11:28 UTC, AvdLee approved these changes

2022-08-10 11:28 UTC, merged

2022-08-10 11:30 UTC, wetransferplatform commented
Congratulations! :tada: This was released as part of [Release 2.7.0](https://github.com/WeTransfer/Mocker/releases/tag/2.7.0) :rocket:<p align="right"><i>Generated by <a href="https://github.com/WeTransfer/GitBuddy">GitBuddy</a></i></p>

2022-10-08 20:13 UTC, rogerluan reviewed
This PR made release v2.7.0 break the contract (APIs), thus who updated from 2.6.0, this change broke their envs. Was this expected? Shouldn't this have been a major version bump (e.g. v3.0.0)? 😬 @batuhansk @AvdLee

2022-10-10 07:30 UTC, AvdLee commented
> This PR made release v2.7.0 break the contract (APIs), thus who updated from 2.6.0, this change broke their envs. Was this expected? Shouldn't this have been a major version bump (e.g. v3.0.0)? 😬 @batuhansk @AvdLee

Ah, you're right! That went unnoticed, mostly since I think I thought `Any` would allow existing code to continue. We've didn't notice much issues on our side at least.

Did you run into many build errors?

2022-10-10 12:42 UTC, rogerluan commented
Yes, our tests started failing upon upgrading from v2.6.0 to v2.7.0, so for now we locked on v2.6.0 (`.exact("2.6.0")`) until we (you and I?) figure out the versioning of Mocker... I think there are a few options:

- a. Revert this PR, and re-release v2.7.0 without it (force push tags and so on - this requires rewriting git history). Then release this PR as part of v3.0.0 (since it includes a breaking change). Down side of this is that whoever has already updated their tests to the new interface will have to undo.

- b. Revert this PR, and release v2.8.0. This doesn't require rewriting git history. There is no down side to this, except who decides to upgrade to the latest version again (v2.8.0) will have to revert their interface changes.

- c. Keep everything as is and force everyone to update their code if they wanna use v2.7.0. 

- d. Create workarounds/adapt this PR to be backwards compatible in its interface. This requires re-thinking the approach of this PR, thus it's the highest-effort solution IMO. Might not even be possible without changing the interface. Once we figure out if this is possible, implement it and release as either v2.7.0 (force push), or a new v2.8.0.

Whatever way we decide, we have to inform users how to migrate from one to another I think (regardless if they're doing this in v2.7.0, v2.8.0 or v3.0.0). This can be done via a e.g. `MIGRATION.md` or just release notes.

WDYT @AvdLee ?

2022-10-11 18:01 UTC, AvdLee commented
Could you show me the errors you got? Would be great if we can open a branch with that error reproduced. That way, I could play around with the API and make the code work for both backwards compatibility, as well for @batuhansk's case

2022-10-12 22:46 UTC, rogerluan commented
I don't have the build logs anymore and would take some time to reproduce the environment in which this occurs, but the error was here:

```swift
mock.onRequest = { _, body in
    guard let body = body else { return }
    XCTAssertEqual(body["answers"] as? [String], answers)
    parametersExpectation.fulfill()
}
```

`body` in v2.6.0 is a `[String:Any]` whereas in v2.7.0 it's `Any`. Perhaps if I blindly casted it to `[String:Any]` it would work, but I didn't check it back then and decided to go for the safest route first.

So the error was like "body of type Any doesn't have a subscript etc…" something along those lines :)

Does this help @AvdLee ? 🙇

2022-10-17 07:38 UTC, AvdLee commented
@rogerluan makes sense! I've opened an issue here: https://github.com/WeTransfer/Mocker/issues/132

I can't promise any timelines here, but feel free to jump on it if you have the time!

2022-11-04 13:43 UTC, wetransferplatform commented
Congratulations! :tada: This was released as part of [Release 3.0.0](https://github.com/WeTransfer/Mocker/releases/tag/3.0.0) :rocket:<p align="right"><i>Generated by <a href="https://github.com/WeTransfer/GitBuddy">GitBuddy</a></i></p>