mixing in the ability to send an explicit error from a mock response
WeTransfer/Mocker pull request #52
Opened 2020-04-17 19:14 UTC by heckj

this is done primarily In order to test error handling - which comes in useful when you're building declarative pipelines that do just that with something like Combine

2020-04-20 12:31 UTC, AvdLee requested changes

2020-04-20 12:31 UTC, AvdLee commented on Sources/Mock.swift
> +    private init(url: URL? = nil, ignoreQuery: Bool = false, reportFailure: Bool = false, dataType: DataType, statusCode: Int, data: [HTTPMethod: Data], additionalHeaders: [String: String] = [:], fil
Wouldn't it make more sense to rename this like:

```suggestion
    private init(url: URL? = nil, ignoreQuery: Bool = false, requestError: Error? = nil, dataType: DataType, statusCode: Int, data: [HTTPMethod: Data], additionalHeaders: [String: String] = [:], fileExtensions: [String]? = nil) {
```

This allows to set explicit types of errors and allows more usecases. We could then simply verify whether this value is set and report a failure instead if so.

2020-04-20 12:32 UTC, AvdLee commented
@heckj thanks for your contribution! I'd love to adjust the code a bit, update the documentation and add some tests. If you would be able to add that, we can merge this in!

2020-04-20 15:57 UTC, heckj commented
I can definitely do that - might be a few days, but hopefully not as long as the first wait ;-)

2020-05-21 19:48 UTC, heckj commented
:wave: @AvdLee - I updated this PR a while ago, so I think it's just waiting on your approval for anything further.

2020-05-22 10:09 UTC, AvdLee approved these changes
Thanks, this looks great! Sorry for not coming back to this any earlier. I think it slipped through somehow!

2020-05-22 10:22 UTC, merged